### PR TITLE
admob banner ad

### PR DESCRIPTION
**Pull request by BalDhaker**
I have integrated the admob plus banner ad at the bottom of the screen and tested.

Please have a look and get back to me.
Thanks

### CODE REVIEW

**Comment by Mr-Kumar-Abhishek** [comment]
Is this you ? confirming https://www.freelancer.in/u/babulalchoudhar1?projectId=38791959

**Comment by Mr-Kumar-Abhishek** [comment]
Could you confirm your username in freelancer ?

**Comment by BalDhaker** [comment]
No I could not bid on the project. My username on freelancer is baldhaker

**Comment by BalDhaker** [comment]
https://www.freelancer.com/u/baldhaker
I have sent you an email, you can reply to that.

**Comment by Mr-Kumar-Abhishek** [comment]
I cannot see the ads yet build of your code yet though ? Are you using admob test ad ids ? https://developers.google.com/admob/android/test-ads

**Comment by BalDhaker** [comment]
Yes I used the test app Id and test ad unit ID. I am able to see the test ad, I can send the apk if you need. So you can try in your device. You might be missing something. I can help in that.

**Comment by Mr-Kumar-Abhishek** [comment]
Okay, I am testing on multiple devices, send the APK we can sort this out. And check the email for my budget.

**Comment by BalDhaker** [comment]
Please checkout the latest commit  above. and try to build again.

**Comment by Mr-Kumar-Abhishek** [comment]
It works but has too many banners on navigation.

**Comment by BalDhaker** [comment]
Fixed.

**Comment by Mr-Kumar-Abhishek** [comment]
Merged and made payment. Check email for details.

**Pull request merged**
